// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Exira.Serilog")]
[assembly: AssemblyProductAttribute("Exira.Users")]
[assembly: AssemblyDescriptionAttribute("Exira.Users is an event sourced microservice to manage users.")]
[assembly: AssemblyVersionAttribute("0.5.0")]
[assembly: AssemblyFileVersionAttribute("0.5.0")]
[assembly: AssemblyMetadataAttribute("githash","98789c22fb9dbcec6f79028b6f039e8bccb4aa9c")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.0";
    }
}
